import os
import sys

env=DefaultEnvironment().Clone()
env.ParseConfig("pkg-config python3 --cflags --libs")

BIN_DIR=os.environ['BIN_DIR'];

env.Program(os.path.join(BIN_DIR, 'awtkRun'), ['assets.c', 'c/awtk_module.c', 'c/main.c']);
