import os
import sys
import platform

OS_NAME = platform.system();
env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

if OS_NAME != 'Windows':
  env.ParseConfig("pkg-config python3 --cflags --libs")

env.Program(os.path.join(BIN_DIR, 'awtkRun'), [Glob('assets*.c'), 'c/awtk_module.c', 'c/main.c']);
